anguage: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker pull apacheignite/ignite
  - docker run -d -p 47100:47100 apacheignite/ignite
  - docker ps -a
script: sh gradlew cleanTest check